name: CI

on: push

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Docker
        uses: docker/login-action@v3
        with:
          username: ${{ secrets.DOCKER_USERNAME }}
          password: ${{ secrets.DOCKER_PASSWORD }}

      - name: Build and push Docker image
        uses: docker/build-push-action@v5
        with:
          push: true
          tags: ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.DOCKERHUB_REPOSITORY }}:latest

      - name: Install SonarScanner
        uses: sonarsource/sonar-scanner-cli@v1.7.0

      - name: Run SonarQube analysis
        run: |
          sonar-scanner \
          -Dsonar.projectKey=${{ secrets.SONAR_PROJECT_KEY }} \ 
          -Dsonar.sources=./src \
          -Dsonar.host.url=${{ secrets.SONAR_URL }}  
          -Dsonar.login=${{ secrets.SONAR_TOKEN }} 
